name: Run test
on: [push, pull_request]
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - run: cmake --version

      - run: pip install -r requirements.txt

      - run: py.test -vv autocmake/*

      - run: py.test -vv test/test.py
